import KpiCard from '../components/KpiCard';
import {Bars,ChartCard,Line} from '../components/Charts';
export default function Dashboard({stats,traffic,alertCharts,recentAlerts=[]}){
 const timeline=traffic.timeline||[], alerts=alertCharts.timeline||[];
 return <>
  <div className="page-head"><div><span className="eyebrow">SECURITY OVERVIEW</span><h1>Network defense posture</h1><p>Synthetic flow telemetry · hybrid detection · analyst-ready context</p></div><div className="scope"><span>Simulation scope</span><b>Reserved IP ranges only</b></div></div>
  <div className="kpi-grid"><KpiCard label="Total network flows" value={stats.total} detail="Processed records"/><KpiCard label="Normal traffic" value={stats.normal} detail="Within baseline" tone="blue"/><KpiCard label="Suspicious traffic" value={stats.suspicious} detail="Needs context" tone="amber"/><KpiCard label="Open alerts" value={stats.open_alerts} detail="New + investigating" tone="violet"/><KpiCard label="Critical alerts" value={stats.critical_alerts} detail="Prioritize review" tone="red"/><KpiCard label="Average risk score" value={stats.average_risk} detail="0–100 calibrated scale" tone="slate"/></div>
  <div className="chart-grid"><ChartCard title="Traffic over time" subtitle="Flow volume by minute" wide><Line data={timeline} field="flows"/></ChartCard><ChartCard title="Normal vs suspicious" subtitle="Final hybrid classification"><Bars data={traffic.classification_distribution}/></ChartCard>
  <ChartCard title="Alerts by severity" subtitle="Triage queue composition"><Bars data={alertCharts.severity_distribution}/></ChartCard><ChartCard title="Top alert types" subtitle="Most frequent detection reasons"><Bars data={alertCharts.top_alert_types}/></ChartCard><ChartCard title="Protocol distribution" subtitle="Observed transport/network protocols"><Bars data={traffic.protocol_distribution}/></ChartCard><ChartCard title="Destination ports" subtitle="Most contacted services"><Bars data={traffic.port_distribution}/></ChartCard><ChartCard title="Top alert sources" subtitle="Synthetic sources by alert volume"><Bars data={alertCharts.top_sources}/></ChartCard><ChartCard title="Risk score distribution" subtitle="Alert risk bands"><Bars data={alertCharts.risk_distribution}/></ChartCard></div>
  <div className="section-title"><div><span className="eyebrow">TRAFFIC ANALYTICS</span><h2>Network behavior timelines</h2></div><p>Rate and failure views help analysts compare bursts, load, and detection context.</p></div>
  <div className="chart-grid"><ChartCard title="Packets per second" subtitle="Traffic-rate signal"><Line data={timeline} field="packets_per_second" color="#56b4ff"/></ChartCard><ChartCard title="Bytes per second" subtitle="Volume and exfiltration context"><Line data={timeline} field="bytes_per_second" color="#b78cff"/></ChartCard><ChartCard title="Connections per minute" subtitle="Session-frequency signal"><Line data={timeline} field="connections" color="#4de2c5"/></ChartCard><ChartCard title="Failed connections" subtitle="Authentication/connectivity failures"><Line data={timeline} field="failed_connections" color="#ff6b7a"/></ChartCard><ChartCard title="Alert timeline" subtitle="Detection volume by minute"><Line data={alerts} field="alerts" color="#f9b84b"/></ChartCard><ChartCard title="Risk timeline" subtitle="Average hybrid risk over time"><Line data={timeline} field="average_risk" color="#fd8a5e"/></ChartCard></div>
  <div className="section-title"><div><span className="eyebrow">RECENT DETECTIONS</span><h2>Latest alerts</h2></div><p>Time, endpoints, protocol, type, severity, risk and workflow state.</p></div>
  <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Time</th><th>Source IP</th><th>Destination IP</th><th>Protocol</th><th>Alert</th><th>Severity</th><th>Risk</th><th>Status</th></tr></thead><tbody>{recentAlerts.slice(0,10).map(a=><tr key={a.alert_id}><td className="mono">{new Date(a.created_at).toLocaleString()}</td><td>{a.source_ip}</td><td>{a.destination_ip}</td><td><span className="proto">{a.protocol}</span></td><td>{a.alert_type}</td><td><span className={`severity ${a.severity.toLowerCase()}`}>{a.severity}</span></td><td><strong className="risk">{a.risk_score.toFixed(1)}</strong></td><td><span className="status">{a.status.replace('_',' ')}</span></td></tr>)}</tbody></table>{!recentAlerts.length&&<div className="empty big">No recent alerts.</div>}</div></section>
 </>
}
