import {useCallback,useEffect,useState} from 'react';
import {Activity,AlertTriangle,LayoutDashboard,Radio,ShieldCheck} from 'lucide-react';
import {api} from './services/api'; import Dashboard from './pages/Dashboard'; import Alerts from './pages/Alerts'; import Investigation from './pages/Investigation';
const emptyTraffic={timeline:[],classification_distribution:[],protocol_distribution:[],port_distribution:[]}; const emptyAlerts={timeline:[],severity_distribution:[],top_alert_types:[],top_sources:[],risk_distribution:[]};
const POLL_INTERVAL=Math.max(1000,Number(import.meta.env.VITE_POLL_INTERVAL_MS||5000));
export default function App(){const query=new URLSearchParams(window.location.search); const [page,setPage]=useState(query.get('page')==='alerts'?'alerts':'dashboard'),[stats,setStats]=useState({}),[traffic,setTraffic]=useState(emptyTraffic),[charts,setCharts]=useState(emptyAlerts),[alerts,setAlerts]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[updated,setUpdated]=useState(null),[filters,setFilters]=useState({severity:'',protocol:'',alert_type:'',status:'',time_range:''});
 const loadDashboard=useCallback(async()=>{try{const [s,t,c]=await Promise.all([api.get('/api/dashboard/stats'),api.get('/api/dashboard/traffic'),api.get('/api/dashboard/alerts')]);setStats(s);setTraffic(t);setCharts(c);setUpdated(new Date());setError('')}catch(e){setError(e.message)}},[]);
 const loadAlerts=useCallback(async()=>{try{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const d=await api.get(`/api/alerts?${q}`);setAlerts(d.items);setError('')}catch(e){setError(e.message)}},[filters]);
 useEffect(()=>{loadDashboard();const id=setInterval(loadDashboard,POLL_INTERVAL);return()=>clearInterval(id)},[loadDashboard]); useEffect(()=>{loadAlerts();const id=setInterval(loadAlerts,POLL_INTERVAL);return()=>clearInterval(id)},[loadAlerts]);
 useEffect(()=>{const deepLink=query.get('alert');if(deepLink)openAlert(deepLink)},[]);
 async function openAlert(id){try{setSelected(await api.get(`/api/alerts/${id}`));setPage('investigation')}catch(e){setError(e.message)}} async function changeStatus(status){try{setSelected(await api.put(`/api/alerts/${selected.alert_id}/status`,{status}));await openAlert(selected.alert_id);loadAlerts()}catch(e){setError(e.message)}} async function addNote(note){try{await api.post(`/api/alerts/${selected.alert_id}/notes`,{note});await openAlert(selected.alert_id)}catch(e){setError(e.message)}}
 return <div className="shell"><aside className="sidebar"><div className="brand"><ShieldCheck/><div><b>SentinelFlow</b><span>NETWORK IDS</span></div></div><nav><button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}><LayoutDashboard/>Overview</button><button className={page!=='dashboard'?'active':''} onClick={()=>setPage('alerts')}><AlertTriangle/>Alerts <em>{stats.open_alerts||0}</em></button></nav><div className="sensor"><div><Radio/><span>SIMULATOR</span></div><b><i/> Sensor online</b><small>Synthetic flow data only</small></div><div className="ethical"><ShieldCheck/><span>Defensive education<br/>No packet transmission</span></div></aside><main><header className="topbar"><div className="crumb">SOC / <b>{page==='dashboard'?'Overview':page==='alerts'?'Alert queue':'Investigation'}</b></div><div className="top-status"><Activity/><span>Polling every {POLL_INTERVAL/1000}s</span><b>{updated?updated.toLocaleTimeString():'Connecting…'}</b></div></header><div className="content">{error&&<div className="error">API: {error}</div>}{page==='dashboard'&&<Dashboard stats={stats} traffic={traffic} alertCharts={charts} recentAlerts={alerts}/>} {page==='alerts'&&<Alerts alerts={alerts} filters={filters} setFilters={setFilters} onOpen={openAlert}/>} {page==='investigation'&&<Investigation alert={selected} onBack={()=>setPage('alerts')} onStatus={changeStatus} onNote={addNote}/>}</div><footer>SentinelFlow IDS Simulation · Synthetic RFC 5737 addresses · Analyst judgment required</footer></main></div>}
